import {levels} from './levels.js';
import {createGame,stepGame,validateStroke,totalInk,strokeLength,WIDTH,HEIGHT} from './engine.js';
const $=id=>document.getElementById(id), canvas=$('board'), c=canvas.getContext('2d');
const KEY='honeyline-rescue-v1';let saved={unlocked:1,stars:{}};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Number.isFinite(s.unlocked)){saved.unlocked=Math.max(1,Math.min(levels.length,s.unlocked));saved.stars={};for(let i=0;i<levels.length;i++){const v=s.stars?.[i];if(Number.isInteger(v)&&v>=1&&v<=3)saved.stars[i]=v;}}}catch{}
let index=0,strokes=[],active=null,pointer=null,game=null,mode='draw',showHint=false,last=0,anim=0,toastTimer,sound=false,ac=null;
const level=()=>levels[index];
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400);}
function tone(freq,duration=.1){if(!sound)return;try{ac??=new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.05,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration);}catch{}}
function cancelDraw(){active=null;if(pointer!==null){try{canvas.releasePointerCapture(pointer);}catch{}pointer=null;}}
function load(n){cancelDraw();index=n;strokes=[];game=null;mode='draw';showHint=false;$('overlay').hidden=true;$('levelNo').textContent=String(n+1).padStart(2,'0');$('levelName').textContent=level().name;$('chapter').textContent=`${String(n+1).padStart(2,'0')} / ${levels.length}`;$('tip').textContent=level().tip;update();}
function update(){const remaining=Math.max(0,1-(totalInk(strokes)+(active?strokeLength(active):0))/level().ink);$('inkFill').style.width=`${remaining*100}%`;$('inkFill').style.background=remaining<.2?'#e49c69':'#a3b16f';$('inkText').textContent=`${Math.round(remaining*100)}%`;$('timeText').textContent=game?`剩下 ${Math.max(0,level().seconds-game.elapsed).toFixed(1)} 秒`:`守護 ${level().seconds} 秒`;$('phase').textContent=mode==='running'?'蜜蜂出動！':mode==='paused'?'休息一下':mode==='won'?'野餐保衛成功':mode==='lost'?'再試一種畫法':'畫好線，再放出蜜蜂';$('start').disabled=mode!=='draw';$('undo').disabled=mode!=='draw'||!strokes.length;$('hint').disabled=mode!=='draw';$('pause').disabled=!['running','paused'].includes(mode);$('pause').textContent=mode==='paused'?'▶':'Ⅱ';$('pause').setAttribute('aria-label',mode==='paused'?'繼續遊戲':'暫停遊戲');$('progressText').textContent=`${Object.keys(saved.stars).length} / ${levels.length}`;$('progressDots').innerHTML=levels.map((_,i)=>`<span class="${saved.stars[i]?'done':''}"></span>`).join('');}
function finish(){mode=game.status;cancelDraw();$('overlay').hidden=false;const win=mode==='won';$('resultIcon').textContent=win?'✦':'☁';$('resultKicker').textContent=win?'PICNIC SAVED':'A LITTLE MORE IMAGINATION';$('resultTitle').textContent=win?'野餐保衛成功！':'哎呀，有蜜蜂溜進來！';let stars=0;if(win){const used=totalInk(strokes)/totalInk(level().solution);stars=used<=1.03?3:used<=1.12?2:1;saved.stars[index]=Math.max(saved.stars[index]||0,stars);saved.unlocked=Math.min(levels.length,Math.max(saved.unlocked,index+2));try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{toast('瀏覽器無法儲存進度，本次仍可繼續玩。');}tone(660,.25);setTimeout(()=>tone(880,.35),100);}else tone(180,.25);$('stars').textContent=win?'★'.repeat(stars)+'☆'.repeat(3-stars):'';$('resultText').textContent=win?(index===levels.length-1?'所有野餐地點都安全了。回到地圖，用更少墨水收集三顆星吧！':'糯米兔謝謝你！試著用更少的墨水，挑戰三顆星。'):'看看防線有沒有缺口，也可以利用石牆，省下更多墨水。';$('resultAction').textContent=win?(index===levels.length-1?'查看守護足跡 →':'下一個野餐地點 →'):'再試一次 ↻';$('resultRetry').hidden=!win;update();$('resultAction').focus();}
function start(){if(mode!=='draw')return;cancelDraw();try{game=createGame(level(),strokes);}catch{toast('這條線太靠近兔子或蜂巢，請重畫。');return;}showHint=false;mode='running';tone(440);update();}
function pause(){if(mode==='running'){mode='paused';$('overlay').hidden=false;$('resultIcon').textContent='Ⅱ';$('resultKicker').textContent='TAKE A LITTLE BREATHER';$('resultTitle').textContent='野餐暫停中';$('resultText').textContent='蜜蜂也休息了，準備好再繼續。';$('stars').textContent='';$('resultAction').textContent='繼續守護 →';$('resultRetry').hidden=true;}else if(mode==='paused'){mode='running';$('overlay').hidden=true;}update();}
function openMap(){if(mode==='running')pause();cancelDraw();update();$('levelGrid').innerHTML=levels.map((l,i)=>`<button class="level-tile ${index===i?'current':''}" data-level="${i}" ${i>=saved.unlocked?'disabled':''}><strong>${i>=saved.unlocked?'⌑':String(i+1).padStart(2,'0')}</strong><small>${l.name}</small><span class="tile-stars">${saved.stars[i]?'★'.repeat(saved.stars[i])+'☆'.repeat(3-saved.stars[i]):i>=saved.unlocked?'尚未解鎖':'等你挑戰'}</span></button>`).join('');$('map').showModal();}
$('start').onclick=start;$('retry').onclick=()=>load(index);$('undo').onclick=()=>{if(mode==='draw'){cancelDraw();strokes.pop();update();}};$('hint').onclick=()=>{showHint=!showHint;toast(showHint?level().tip:'提示已隱藏');};$('pause').onclick=pause;$('levels').onclick=openMap;$('closeMap').onclick=()=>$('map').close();$('map').addEventListener('click',e=>{const b=e.target.closest('[data-level]');if(b&&!b.disabled){load(+b.dataset.level);$('map').close();}});$('resultAction').onclick=()=>{if(mode==='paused')pause();else if(mode==='won'&&index<levels.length-1)load(index+1);else if(mode==='won')openMap();else load(index);};$('resultRetry').onclick=()=>load(index);$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-label',sound?'關閉音效':'開啟音效');$('sound').querySelector('span').style.background=sound?'#6d8b61':'#dd986e';if(sound)tone(660);};
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*WIDTH/r.width,y:(e.clientY-r.top)*HEIGHT/r.height};}
canvas.addEventListener('pointerdown',e=>{if(mode!=='draw'||pointer!==null||e.button>0)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);active=[point(e)];showHint=false;});
function appendPoint(p){if(!active)return;const prev=active.at(-1),len=Math.hypot(p.x-prev.x,p.y-prev.y);if(len<2)return;const budget=level().ink-totalInk(strokes)-strokeLength(active);if(budget<=.001)return;const portion=Math.min(1,budget/len);active.push({x:prev.x+(p.x-prev.x)*portion,y:prev.y+(p.y-prev.y)*portion});}
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||!active)return;e.preventDefault();const events=e.getCoalescedEvents?.();for(const ev of events?.length?events:[e])appendPoint(point(ev));update();});
canvas.addEventListener('pointerup',e=>{if(e.pointerId!==pointer)return;appendPoint(point(e));const candidate=active;cancelDraw();if(candidate?.length>1){const v=validateStroke(level(),strokes,candidate);if(v.ok){strokes.push(v.stroke);tone(530,.04);}else toast(v.reason||'請避開兔子、蜂巢和石牆再畫一次。');}update();});
canvas.addEventListener('pointercancel',()=>{cancelDraw();update();});canvas.addEventListener('lostpointercapture',()=>{if(active){cancelDraw();update();}});window.addEventListener('resize',()=>{cancelDraw();update();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='running')pause();});window.addEventListener('keydown',e=>{if($('map').open)return;if(e.key.toLowerCase()==='r')load(index);if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();$('undo').click();}if(e.code==='Space'&&e.target===canvas){e.preventDefault();mode==='draw'?start():pause();}});
function round(x,y,w,h,r=12){c.beginPath();c.roundRect(x,y,w,h,r);}
function ellipse(x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill();}
function line(points,color='#304c3b',width=10,dash=[]){if(points.length<2)return;c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.setLineDash(dash);c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();c.setLineDash([]);}
function flower(x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#aab78c';c.lineWidth=2;c.beginPath();c.moveTo(0,0);c.lineTo(0,12);c.stroke();for(let i=0;i<5;i++){const a=i*Math.PI*2/5;ellipse(Math.cos(a)*4,Math.sin(a)*4,3.2,3.2,'#f5f2cd');}ellipse(0,0,2.4,2.4,'#d8b86a');c.restore();}
function rabbit(t,i){const bob=mode==='draw'?Math.sin(anim*2+i)*1.2:0;c.save();c.translate(t.x,t.y+bob);ellipse(0,20,23,5,'#778c5625');c.save();c.rotate(-.15);ellipse(-9,-20,6,15,'#fffbed');ellipse(-9,-21,2.4,9,'#edc2b6');c.restore();c.save();c.rotate(.16);ellipse(9,-20,6,15,'#fffbed');ellipse(9,-21,2.4,9,'#edc2b6');c.restore();ellipse(0,3,21,20,'#fffbed');ellipse(-7,20,7,3.5,'#f3e9d6');ellipse(7,20,7,3.5,'#f3e9d6');ellipse(-13,7,4,2.5,'#f2c1aa');ellipse(13,7,4,2.5,'#f2c1aa');c.strokeStyle='#4b5140';c.lineWidth=2.4;c.lineCap='round';if(mode==='won'){line([{x:-9,y:1},{x:-6,y:-1},{x:-3,y:1}],'#4b5140',2);line([{x:3,y:1},{x:6,y:-1},{x:9,y:1}],'#4b5140',2);}else{ellipse(-6,1,1.6,2.1,'#434c39');ellipse(6,1,1.6,2.1,'#434c39');}ellipse(0,6,2,1.5,'#b17b68');c.beginPath();c.arc(0,7,3,0,Math.PI);c.stroke();c.fillStyle='#dc9770';c.beginPath();c.moveTo(-14,16);c.lineTo(14,16);c.lineTo(6,22);c.lineTo(-7,22);c.closePath();c.fill();c.restore();}
function hive(h){c.save();c.translate(h.x,h.y);c.strokeStyle='#936e3c';c.lineWidth=2;c.beginPath();c.moveTo(0,-35);c.lineTo(0,-25);c.stroke();ellipse(0,24,26,5,'#778c5620');for(let i=0;i<5;i++){const y=-17+i*8,rx=[14,21,25,26,21][i];ellipse(0,y,rx,8,['#e3b35b','#f1c776','#e9b95f','#dfac50','#d19b48'][i]);}ellipse(8,9,6,7,'#795934');c.fillStyle='#815e36';c.font='bold 9px sans-serif';c.textAlign='center';c.fillText('BUZZ',0,-3);c.restore();}
function bee(b){c.save();c.translate(b.x,b.y);c.rotate(Math.atan2(b.vy||0,b.vx||1));const wing=Math.sin(anim*40+b.id)*2;ellipse(-2,-6,5,5+wing,'#fffdf0d9');ellipse(-2,6,5,5-wing,'#fffdf0d9');ellipse(0,0,10,6.5,'#f0bf57');c.save();c.beginPath();c.ellipse(0,0,10,6.5,0,0,Math.PI*2);c.clip();c.fillStyle='#544b34';c.fillRect(-6,-7,3,14);c.fillRect(0,-7,3,14);c.restore();ellipse(6,-2,1.3,1.3,'#544b34');c.fillStyle='#544b34';c.beginPath();c.moveTo(-9,-2);c.lineTo(-13,0);c.lineTo(-9,2);c.fill();c.restore();}
function render(){c.clearRect(0,0,WIDTH,HEIGHT);c.fillStyle='#edf2dd';c.fillRect(0,0,WIDTH,HEIGHT);c.fillStyle='#dce6c430';for(let y=16;y<600;y+=29)for(let x=17;x<720;x+=29){c.beginPath();c.arc(x,y,.9,0,7);c.fill();}c.fillStyle='#e4ebce';c.beginPath();c.moveTo(0,490);c.bezierCurveTo(130,435,240,550,360,504);c.bezierCurveTo(510,435,560,468,720,490);c.lineTo(720,600);c.lineTo(0,600);c.fill();c.globalAlpha=.55;[[75,78,1],[618,96,.8],[535,42,.6]].forEach(([x,y,s])=>{ellipse(x,y,32*s,9*s,'#fffdf1');ellipse(x-12*s,y-5*s,15*s,12*s,'#fffdf1');ellipse(x+9*s,y-8*s,17*s,15*s,'#fffdf1');});c.globalAlpha=1;
for(const t of level().terrain){c.fillStyle='#bac895';round(t.x,t.y,t.w,t.h,Math.min(12,t.w/2,t.h/2));c.fill();c.save();round(t.x,t.y,t.w,t.h,Math.min(12,t.w/2,t.h/2));c.clip();c.fillStyle='#a8b985';c.fillRect(t.x,t.y,t.w,9);c.fillStyle='#ced7b0';for(let x=t.x+16;x<t.x+t.w;x+=38)for(let y=t.y+26;y<t.y+t.h;y+=34){round(x,y,12,3,2);c.fill();}c.restore();}
[[38,565,.8],[670,549,1],[577,569,.7],[143,578,.8],[629,587,.7],[91,543,.6]].forEach(v=>flower(...v));
if(showHint)for(const s of level().solution)line(s,'#8fa27f88',6,[7,10]);for(const s of strokes){line(s,'#fffbed80',14);line(s);}if(active){const v=active.length>1?validateStroke(level(),strokes,active):{ok:true};line(active,v.ok?'#3d604a':'#c98666',10);const p=active.at(-1);ellipse(p.x,p.y,5,5,'#e8ba6d');}
level().hives.forEach(hive);level().targets.forEach(rabbit);if(game)game.bees.forEach(bee);else level().hives.forEach((h,i)=>bee({x:h.x+35,y:h.y-16+Math.sin(anim*3+i)*3,id:i,vx:-1,vy:0}));
if(mode==='draw'&&!strokes.length&&!active){c.textAlign='center';c.fillStyle='#758667';c.font='12px sans-serif';c.fillText(index===0?'拖曳畫線，給糯米兔一個安全的小窩':'先觀察地形，再畫出你的防線',WIDTH/2,HEIGHT-19);}if(mode==='running'){c.fillStyle='#fffdf1e8';round(306,14,108,35,17);c.fill();c.textAlign='center';c.fillStyle='#486144';c.font='bold 14px sans-serif';c.fillText(`守護 ${Math.max(0,level().seconds-game.elapsed).toFixed(1)} s`,360,37);}}
function frame(ts){const dt=Math.min((ts-last)/1000||0,1/20);last=ts;if(mode!=='paused')anim+=dt;if(mode==='running'){stepGame(game,dt);if(game.status!=='running')finish();update();}render();requestAnimationFrame(frame);}load(0);requestAnimationFrame(frame);
